[DevDependency] Bump activesupport from 7.0.4.2 to 7.0.7 (#525)
Bumps [activesupport](https://github.com/rails/rails) from 7.0.4.2 to
7.0.7.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activesupport's
releases</a>.</em></p>
<blockquote>
<h2>7.0.7</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>Cache::NullStore</code> with local caching for repeated
reads.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix <code>to_s</code> with no arguments not respecting custom
<code>:default</code> formats</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising
<code>NoMethodError: undefined method `end_with?' for
nil:NilClass</code>.</p>
<p><em>James Robinson</em></p>
</li>
<li>
<p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p>
<p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan
Hefner</em></p>
</li>
<li>
<p>Improve error message when EventedFileUpdateChecker is used without a
compatible version of the Listen gem</p>
<p><em>Hartley McGuire</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Error.full_message now strips &quot;:base&quot; from the message.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Add a load hook for <code>ActiveModel::Model</code> (named
<code>active_model</code>) to match the load hook for
<code>ActiveRecord::Base</code> and allow for overriding aspects of the
<code>ActiveModel::Model</code> class.</p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Restores functionality to the missing method when using enums and
fixes.</p>
<p><em>paulreece</em></p>
</li>
<li>
<p>Fix <code>StatementCache::Substitute</code> with serialized type.</p>
<p><em>ywenc</em></p>
</li>
<li>
<p>Fix <code>:db_runtime</code> on notification payload when application
have multiple databases.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/blob/v7.0.7/activesupport/CHANGELOG.md">activesupport's
changelog</a>.</em></p>
<blockquote>
<h2>Rails 7.0.7 (August 09, 2023)</h2>
<ul>
<li>
<p>Fix <code>Cache::NullStore</code> with local caching for repeated
reads.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix <code>to_s</code> with no arguments not respecting custom
<code>:default</code> formats</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising
<code>NoMethodError: undefined method `end_with?' for
nil:NilClass</code>.</p>
<p><em>James Robinson</em></p>
</li>
<li>
<p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p>
<p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan
Hefner</em></p>
</li>
<li>
<p>Improve error message when EventedFileUpdateChecker is used without a
compatible version of the Listen gem</p>
<p><em>Hartley McGuire</em></p>
</li>
</ul>
<h2>Rails 7.0.6 (June 29, 2023)</h2>
<ul>
<li>
<p>Fix <code>EncryptedConfiguration</code> returning incorrect values
for some <code>Hash</code>
methods</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix arguments being destructed <code>Enumerable#many?</code> with
block.</p>
<p><em>Andrew Novoselac</em></p>
</li>
<li>
<p>Fix humanize for strings ending with id.</p>
<p><em>fatkodima</em></p>
</li>
</ul>
<h2>Rails 7.0.5.1 (June 26, 2023)</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Rails 7.0.5 (May 24, 2023)</h2>
<ul>
<li>
<p>Fixes TimeWithZone ArgumentError.</p>
<p><em>Niklas Häusele</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/522c86f35ccc80453ed9fb6ca8b394db321f9a69"><code>522c86f</code></a>
Preparing for 7.0.7 release</li>
<li><a
href="https://github.com/rails/rails/commit/5610cbacc5630d775a1a7be78ccb17e561908cba"><code>5610cba</code></a>
Sync CHANGELOG with the changes in the repository</li>
<li><a
href="https://github.com/rails/rails/commit/7e9ffc2e137b649c6fd2ca1c580cdfffc9845b55"><code>7e9ffc2</code></a>
Fix to_s not using :default format with no args</li>
<li><a
href="https://github.com/rails/rails/commit/a8e88e2e4f157e47050d4ba17ea936902f6a2994"><code>a8e88e2</code></a>
Fix <code>Cache::NullStore</code> with local caching for repeated
reads</li>
<li><a
href="https://github.com/rails/rails/commit/b18b9df65eb7d4e5dfa9a6982a8709c0c94b0b97"><code>b18b9df</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/48800">#48800</a>
from robinjam/fix-humanize-nil</li>
<li><a
href="https://github.com/rails/rails/commit/b12fe80d17b2c7a2cc083d0c83ae3ed95765e6bd"><code>b12fe80</code></a>
Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code></li>
<li><a
href="https://github.com/rails/rails/commit/e3f80f625945c689b5edc473c5132037c0c14952"><code>e3f80f6</code></a>
Add lower bound to Listen gem requirement</li>
<li><a
href="https://github.com/rails/rails/commit/e3f9ef6f704a3a04884ce49577ffaed8038fa621"><code>e3f9ef6</code></a>
Improve error message for missing listen gem</li>
<li><a
href="https://github.com/rails/rails/commit/597e4bb5038714afcdfce2f8410469f3d95a700f"><code>597e4bb</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/48693">#48693</a>
from zzak/bigdecimal-to_s</li>
<li><a
href="https://github.com/rails/rails/commit/92636dacfedad8a4e5871de6ae71e64f3bb8df78"><code>92636da</code></a>
Warm-up to avoid autoloads interfering with class serial</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.0.4.2...v7.0.7">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activesupport&package-manager=bundler&previous-version=7.0.4.2&new-version=7.0.7)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/Submitty/submitty.github.io/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>